# =============================================================================
# Jenkins Service
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30808
    - name: jnlp
      port: 50000
      targetPort: 50000
---
# =============================================================================
# VirtualService for Jenkins
# =============================================================================
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: jenkins
  namespace: jenkins
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/ride-hailing-gateway
  http:
    - match:
        - uri:
            prefix: /github-webhook/
      route:
        - destination:
            host: jenkins.jenkins.svc.cluster.local
            port:
              number: 8080
